create database products;

create table products (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    unit_price decimal(16,2) not null
);

create database clients;

create table clients (
    id bigint generated by default as identity primary key,
    name varchar(150) not null,
    cpf varchar(11) not null,
    street varchar(100),
    number varchar(10),
    neighborhood varchar(100),
    email varchar(150),
    phone varchar(20)
);

create database orders;

create table orders (
    id bigint generated by default as identity primary key,
    client_id bigint not null,
    order_date timestamp not null default now(),
    payment_key text,
    notes text,
    status varchar(20) check (
        status in ('CREATED', 'PAID', 'INVOICED', 'SHIPPED', 'PAYMENT_ERROR', 'PREPARING_SHIPMENT')
        ),total decimal(16,2) not null,
    tracking_code varchar(255),
    invoice_url text
);

create table order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null references orders (id),
    product_id bigint not null,
    quantity int not null,
    unit_price decimal(16,2) not null
);